name: clippy

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: "1.78.0" # MSRV
          components: "clippy"

      - name: Clippy
        run: cargo clippy --workspace --no-deps --all-features --all-targets -- -D warnings
