name: tests

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0

      - name: All features
        run: cargo test --workspace --all-features --all-targets

      - name: No default features
        run: cargo test --workspace --no-default-features --all-targets

  miri:
    name: Miri Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: "nightly"
          components: "miri"

      - name: Run tests
        # Pass -Zmiri-ignore-leaks beause it complains about the global rayon threadpool.
        run: MIRIFLAGS='-Zmiri-tree-borrows -Zmiri-ignore-leaks' cargo miri test --workspace --all-features --all-targets
